[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.12"
tokio = {version="1",features =["full"]}
tokio-tungstenite = "0.21"
serde = {version="1.0",features =["derive"]}
serde_json ="1.0"
